Remove Node.js 14 support
This change adds `engines.node` to `package.json` to pass `npm run release` (`np`).
If `engines.node` is missing, `np` fails:

```
Error: Please include a `engines.node` field in your package.json
```